### ISSUE TITLE
[BUG] Can't import blue prints with crash_site_generator.

### ISSUE THREAD

**Issue by baryluk** [teoxoy/factorio-blueprint-editor#177]
First of all a great job with parsing blueprints and rendering them. Editor is really useful too, and works well even for big blue prints (performance of belt rotation could be improved tho).

Anyway, to the bug.

I have a big blueprint that fails to load.

**Describe the bug**

FBE fails to import some blueprints.

It complains about entityName validation for name of the entity 3020.

I think it is entity `crash_site_generator`.

I often use crash_site_generator when having fun with blueprints and using editor mode in Factorio, and sometimes it does sneak into the blueprint.

One of the options is to support it, another is to simply ignore the `crash_site_generator` and not import these entities. I only use them as a dummy source of electric power for testing, but not having them in the blueprint is also fine.

**To Reproduce**

Use this blueprint in current version FBE, paste it using copy & paste function.

https://gist.githubusercontent.com/baryluk/5b6fc24917a56c8bdaa5b70957f3d959/raw/2cdb9582e30ce04f31c2c3190a216ed8a53c3ba9/greate-lane-randomizer.blueprint.txt

It is pretty big, and has about 4000 entities.

[greate-lane-randomizer.blueprint.txt](https://github.com/Teoxoy/factorio-blueprint-editor/files/3883870/greate-lane-randomizer.blueprint.txt)

**Comment by Teoxoy** [comment]
Thanks for all the bug reports!
I have been busy recently and still didn't get around to finish what I've been working on.
I will look into the issues you brought up as soon as I can though.

**Comment by teoxoy** [comment]
You can use the new `electric_energy_interface` for testing purposes.

Maybe in the future I will ignore unsupported entities. The only issue with that is the fact that this is an editor as well. So the question becomes: How should we ignore unsupported entities while still allowing editing? The first issue I can think of, is not knowing the size of unsupported entities and because of that there would be no collision detection for those items. You could easily put an entity over the unsupported entity.
