### ISSUE TITLE
[BUG] Doesn't render blueprint string with trains on rails

### ISSUE THREAD

**Issue by Bilka2** [Teoxoy/factorio-blueprint-editor#67]
**Describe the bug**
Doesn't render blueprint string at all

**To Reproduce**
Open https://teoxoy.github.io/factorio-blueprint-editor/?source=https://pastebin.com/SSBN2NJv

**Current behavior**
Page loads normally, blueprint editing area is empty.

**Expected behavior**
Page loads normally, shows blueprint.

**Screenshots**
How the blueprint should look like (rendered by https://github.com/demodude4u/Factorio-FBSR)
![bp](https://cdn.discordapp.com/attachments/314607309508575236/594851079254966278/blueprint.png)

**Desktop**

-   OS: Windows 10
-   Browser: Firefox 67.0.4

<details><summary><strong>Blueprint String</strong></summary>
https://pastebin.com/SSBN2NJv
</details>

**Comment by Teoxoy** [comment]
Trains are quite a challenge to implement in the browser and this is because the spritesheets of all train rotations are huge.

Currently all entities are in 1 spritesheet. The HR spritesheet is an 8k texture which is max on most computers so before we add a train spritesheet(s) we need to come up with a way to programmatically split big spritesheets into smaller ones (that's what Factorio does too afaik).

Even with that in place the size of the train spritesheet(s) is something to be thought of.
When it comes to rendering, I guess we can make the app only fetch the spritesheet with the correct train rotation but what happens in the future if we would like to add the ability to move trains?

I have given it some thought even when 0,17 dropped but I got no concrete solution as of now.
Maybe you can give your 2cents on the matter :)

**Comment by Teoxoy** [comment]
The editor will now (8a1ec669a1978e1a9d5c6b1ba709dfa180877e96) show an appropriate error for blueprints with train entities.
Track the progress of trains support in the feature issue.

Thanks for all the bug reports!
